#!/usr/bin/bash
# 
# Script for changing desktop wallpaper using imlibsetroot as backend
# Copyright (c) alphaOS
# Written by simargl <archpup-at-gmail-dot-com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

WALLPAPER=$(gsettings get org.gnome.desktop.background picture-uri | sed 's|file://||g' | cut -c 2-)
WALLPAPER=${WALLPAPER%?}

wallpaper_set()
{
  if [ "$WALLPAPER" ]; then
    echo "Wallpaper image \"$WALLPAPER\""
    imlibsetroot -s f "$WALLPAPER" 2>/dev/null
    if [ $? -ne 0 ]; then
      echo "Failed"
      exit 1
    else
      if [ "$(pidof conky)" ]; then 
        killall conky; conky > /dev/null 2>&1 &
      fi
    fi
  fi
}

wallpaper_init()
{
  if [ "$WALLPAPER" ]; then
    echo "Wallpaper image \"$WALLPAPER\""
    imlibsetroot -s f "$WALLPAPER" 2>/dev/null
    if [ $? -ne 0 ]; then
      echo "Failed"
      exit 1
    fi
  fi
}

case "$1" in
  
  --init)
    wallpaper_init ;;
  
  --set)
    wallpaper_set ;;

esac