#!/bin/dash
########################################################################
# Begin /etc/init.d/vsftpd
#
# Description : Start Very Secure FTP Daemon
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            ftpd
# Required-Start:      $remote_fs
# Should-Start:
# Required-Stop:       $remote_fs
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts vsftpd server.
# Description:         Starts Very Secure FTP Daemon (vsftpd).
# X-LFS-Provided-By:   LFS
### END INIT INFO

#. /lib/lsb/init-functions

#$LastChangedBy: bdubbs $
#$Date: 2011-12-06 02:37:16 +0000 (Tue, 06 Dec 2011) $

case "$1" in
   start)
      echo "Starting vsFTPD Server..."
      vsftpd
      
      ;;

   stop)
      echo "Stopping vsFTPD Server..."
      killall vsftpd
      
      ;;

#   reload)
#      echo "Reloading vsFTPD Server..."
#      pkill /usr/sbin/vsftpd -HUP
      
#      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      pidof vsftpd > /dev/null && echo "vsFtpd is running." || echo "vsFtpd is stopped."
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/vsftpd
