#!/usr/bin/bash
#
# Copyright (c) alphaOS
# Written by simargl <archpup-at-gmail-dot-com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /etc/spkg/main.config
. /etc/spkg/main.functions

case "$1" in

  download|-d)
    PKG="$2"
    spkg_download ;;
  
  extract|-x)
    PKG="$2"
    spkg_download
    spkg_extract ;;   
  
  compile|-c)
    PKG="$2"
    spkg_download
    spkg_extract
    spkg_compile_package ;;

  ci|-ci)
    PKG="$2"
    spkg_download
    spkg_extract
    spkg_compile_package
    spkg_compile_install ;; 

  pack|-pack)
    PACK="$2"
    spkg_pack_folder ;;
    
  arch|-a)
    ARCH="$2"
    spkg_arch2def ;;

  makesb|-makesb)
    spkg_makesb_gzip ;;

  ver|-ver)
    spkg_version_check ;;  

  file|-file)
    SFILE="$2"
    spkg_file_search ;;

  extract|-e)
    SPKG="$2"
    spkg_extract_spkg ;;
  
  eall|-eall)
    spkg_extract_all ;;  
  
  help|-help|--help|-h)
    spkg_help ;;
  
  info|-info)
    PKG="$2"
    spkg_installed_info ;;
    
  -repack)
    REPACK="$2"
    spkg_repack ;;  
      
  install|-i)
    shift 1
    PKG="$@"
    spkg_install_package ;;
   
  remove|-r)
    shift 1
    PKG="$@"
    spkg_remove_package ;;
    
esac
