#!/usr/bin/bash
#
# Copyright (c) alphaOS
# Written by simargl <archpup-at-gmail-dot-com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /$PWD/functions

case "$1" in

  base)
    sb_build_base_module ;;

  extra)
    sb_build_extra_module ;;

  dev)
    sb_build_devel_module ;;

  alphat)
    sb_build_alphat_base ;;

  *)
    echo "sb_build -- Options: base dev extra" ;;

esac
